ALTER TABLE product ADD COLUMN product_url VARCHAR(128) NOT NULL;
ALTER TABLE platform RENAME COLUMN product_url TO url;
ALTER TABLE platform ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
